### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by renius** [shanehofstetter/rails-i18n-vscode#1]
On mouse over it showed 'Loading...' tooltip one time and on mouse out it does not showed anything even on next on mouse over event.
Debug console is empty.
Reproducible after vscode reload.

Thanks

**Comment by shanehofstetter** [comment]
@renius Could you provide me a minimal example project where the problem occurs? It seems like it just can't find the translation of the key which is hovered. I will probably make a change soon, so that a message is displayed if the key was not found.

**Comment by renius** [comment]
@shanehofstetter we have related-microservices with partialy shared codebase. I18n files may be both in shared gems and application. However, if your plugin can't find translation of one key there is no way to understand that plugin tries to find it in another.

Thanks

**Comment by shanehofstetter** [comment]
@renius Currently the I18n load paths are not evaluated (therefore locale files located elsewhere than standard rails path are not found), but I will add this feature soon and let you know.

**Comment by guillaumebriday** [comment]
It does not work for me as well. Is there any requirement about the rails configuration to follow ? Thanks

**Comment by shanehofstetter** [comment]
@guillaumebriday Currently only locale files located in the path `config/locales` (to be exact the regex `config/locales/**/*.yml` is used) are loaded. I will implement a feature in the near future which evaluates the `I18n.load_path` and parses all yaml files located there.

**Comment by guillaumebriday** [comment]
Hum...unfortunately this is where my locale files are.

This is my configuration in the I18n initializer :

```ruby
Rails.application.config.i18n.default_locale = :fr
Rails.application.config.i18n.available_locales = [:fr]
```

I don't have any loading tooltip as well :/

**Comment by shanehofstetter** [comment]
@guillaumebriday Does it not show the tooltip on all i18n keys or just some of them? The loading is only displayed until the plugin is ready or a response is returned - when it does not show anything currently this means that the key could not be found. It would also be of help if you could provide me with a small example project so I can replicate the problem.

**Comment by guillaumebriday** [comment]
In my slim file when I hover the `t('.login')`: 
![screen shot 2018-08-24 at 11 08 00](https://user-images.githubusercontent.com/8252238/44576151-21db1280-a78e-11e8-87a7-9505e672d7e2.png)

In my locale file:
![screen shot 2018-08-24 at 11 08 33](https://user-images.githubusercontent.com/8252238/44576152-21db1280-a78e-11e8-92ae-651bce5317ee.png)

My config file:
![screen shot 2018-08-24 at 11 08 54](https://user-images.githubusercontent.com/8252238/44576153-21db1280-a78e-11e8-8f0f-48e7c2552207.png)

**Comment by shanehofstetter** [comment]
@guillaumebriday Thanks, I looked into it and the problem could have occurred when reading the default locale config. I made some changes and published a new release, could you update the plugin and check if the problem still occurs? If it still doesn't work, it would be great if you set the debug level to 0 in the settings (`railsI18n.debugLevel`) and show me the logs (you can see them in the developer tools).

**Comment by guillaumebriday** [comment]
Yeah ! 🎉 it works fine now 

Thanks @shanehofstetter 👍

**Comment by shanehofstetter** [comment]
@guillaumebriday Great! 
@renius I assume you still have the same issue, however I created a new issue for this #5 so I'm closing this for now
