### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by wonda-tea-coffee** [shanehofstetter/rails-i18n-vscode#16]
- Issue Type: `Performance`
- Extension Name: `rails-i18n`
- Extension Version: `0.3.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/*****/shanehofstetter.rails-i18n-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by pavlitsky** [comment]
I have this issue too. Every time I start VSCode it takes more than 5 minutes for the extension to load. It's consuming CPU at 100% and `Loading translations..` hanging in the status bar blocking loading other extensions.

`railsI18n.loadAllTranslations` is configured as `false`. Setting debug level to 0 doesn't bring any additional info.

Our locale files have 5200 keys over 550 files and two locales. Maybe it's just not suitable for applications having setups like this?

Here's developer console output and some dumps if it helps.
```
WARN UNRESPONSIVE extension host, 'shanehofstetter.rails-i18n' took 97% of 5213.189ms,
saved PROFILE here: '/tmp/exthost-189f91.cpuprofile'
  Array(4)
    0: {id: "gc", total: 170897, percentage: 3}
    1: {id: "program", total: 6364, percentage: 0}
    2: {id: "self", total: 153, percentage: 0}
    3: {id: "shanehofstetter.rails-i18n", total: 5035663, percentage: 97}

[Extension Host] yaml files loaded
[Extension Host] default locale from rails: en workspace dir: argon
[Extension Host] default locales: {/home/pavlitsky/src/simplex/argon: "en"}
[Extension Host] finished loading.
```

[exthost-4db95b.cpuprofile.txt](https://github.com/shanehofstetter/rails-i18n-vscode/files/3604731/exthost-4db95b.cpuprofile.txt)

[exthost-189f91.cpuprofile.txt](https://github.com/shanehofstetter/rails-i18n-vscode/files/3604732/exthost-189f91.cpuprofile.txt)

**Comment by shanehofstetter** [comment]
@wonda-tea-coffee @pavlitsky Thanks for reporting this. 

> Our locale files have 5200 keys over 550 files and two locales. Maybe it's just not suitable for applications having setups like this?

Yes I think the current implementation may not be suitable for large translation bases. The extension requires loading/indexing all translation files into memory at activation/startup. It may be possible to optimize this process though, I'll look into it.

**Comment by shanehofstetter** [comment]
@wonda-tea-coffee @pavlitsky Just published an update which should reduce the cpu-usage during the initial indexing, on my local testing environment it reduced the load time by about 30-40%. Do you notice any improvements?

**Comment by pavlitsky** [comment]
@shanehofstetter as for me it's a huge 300x improvement. The overall extension loading time has dropped from 5.5 minutes to 19 seconds so performance isn't a problem anymore.

> [Extension Host] loading translations took 9148ms

`UNRESPONSIVE extension host` message still appearing from time to time but much less often.
