### ISSUE TITLE
Work with slim

### ISSUE THREAD

**Issue by guillaumebriday** [shanehofstetter/rails-i18n-vscode#2]
Hey ! 

Thank you for you work. Do you think it's possible to add slim support ?

I don't know how to do it but I see in this file https://github.com/shanehofstetter/rails-i18n-vscode/blob/master/src/extension.ts that there is HAML and ERB support only ?

Is it complicated to add [slim](https://github.com/slim-template/slim-rails) ?

Thank you in advance

**Comment by shanehofstetter** [comment]
@guillaumebriday It should actually work right out of the box if the plugin gets registered for slim files too since the ruby syntax is the same. I will add it soon and create a new release.

**Comment by guillaumebriday** [comment]
Yes, this is what I thought !

Thank you 👍

**Comment by shanehofstetter** [comment]
slim support is now added in v0.0.3
